### ISSUE TITLE
lirically get crashed when opened to download liric

### ISSUE THREAD

**Issue by muhammadarif1** [shkcodes/Lyrically#36]
#### Expected behavior
I think I can download the lyrics ofline

#### Actual behavior
when i open this app i try to download but this app even cras
#### How to reproduce
-download app lirically
-lauch the app
-chose option download liric and the app get crashed
* Operating system: advan s5e nxt android lolipop 5.1 idos 
app version; lirically version 0.53

#### Recording Of The Bug
https://www.youtube.com/watch?v=taCIYh-ixLU

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@muhammadarif/lirically-get-crashed-when-opened-to-download-liric">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Limon93** [comment]
I am not able to replicate your crash.
Can you provide names of your songs (mp3 file names)? 
The app crashes before starting to download lyrics, probably during song list collection.
Can you see lyrics in normal mode (swipe up during music play)?

I report everything fully working, normal & offline mode tested.

**Comment by shkcodes** [comment]
I also cannot replicate it. I use the app everyday and it works fine on my end. Can you check if you granted the storage permission? Also, does your phone have an external SD card? I need more information to help you.

**Comment by steelstrings** [comment]
I've got the same problem. For me at least the app (v0.55) crashes when it hits files with certain characters in their filename. The default behaviour of the app is to look up the entire data storage it has access to. But I tend to also have podcasts laying around, therefore I'd suggest adding an option to exclude directories when scanning for lyrics. It seems to happen on qoutes (') and double quoutes (") and other chars (•) too.

```
01-25 19:17:18.755   7000     7024         AndroidRuntime  E  FATAL EXCEPTION: IntentService[FetchLyrics]
01-25 19:17:18.755   7000     7024         AndroidRuntime  E  Process: com.shkmishra.lyrically, PID: 7000
01-25 19:17:18.755   7000     7024         AndroidRuntime  E  java.lang.IllegalArgumentException: Malformed URL: ?q=genius%2B%3Cunknown%3E%2BPorcupine%2BTree%22Sleep%2BTogether%22%2BLive%2Bin%2BTilburg+Lyrics
01-25 19:17:18.755   7000     7024         AndroidRuntime  E  at org.jsoup.helper.HttpConnection.url(HttpConnection.java:76)
01-25 19:17:18.755   7000     7024         AndroidRuntime  E  at org.jsoup.helper.HttpConnection.connect(HttpConnection.java:36)
01-25 19:17:18.755   7000     7024         AndroidRuntime  E  at org.jsoup.Jsoup.connect(Jsoup.java:73)
01-25 19:17:18.755   7000     7024         AndroidRuntime  E  at com.shkmishra.lyrically.FetchLyrics.getLyrics(FetchLyrics.java:94)
01-25 19:17:18.755   7000     7024         AndroidRuntime  E  at com.shkmishra.lyrically.FetchLyrics.onHandleIntent(FetchLyrics.java:49)
01-25 19:17:18.755   7000     7024         AndroidRuntime  E  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
01-25 19:17:18.755   7000     7024         AndroidRuntime  E  at android.os.Handler.dispatchMessage(Handler.java:102)
01-25 19:17:18.755   7000     7024         AndroidRuntime  E  at android.os.Looper.loop(Looper.java:154)
01-25 19:17:18.755   7000     7024         AndroidRuntime  E  at android.os.HandlerThread.run(HandlerThread.java:61)
01-25 19:17:18.755   7000     7024         AndroidRuntime  E  Caused by: java.net.MalformedURLException: no protocol: ?q=genius%2B%3Cunknown%3E%2BPorcupine%2BTree%22Sleep%2BTogether%22%2BLive%2Bin%2BTilburg+Lyrics
01-25 19:17:18.755   7000     7024         AndroidRuntime  E  at java.net.URL.<init>(URL.java:589)
01-25 19:17:18.755   7000     7024         AndroidRuntime  E  at java.net.URL.<init>(URL.java:486)
01-25 19:17:18.755   7000     7024         AndroidRuntime  E  at java.net.URL.<init>(URL.java:435)
01-25 19:17:18.755   7000     7024         AndroidRuntime  E  at org.jsoup.helper.HttpConnection.url(HttpConnection.java:74)
01-25 19:17:18.755   7000     7024         AndroidRuntime  E  ... 8 more
01-25 19:17:18.756   1058    21768        ActivityManager  W  Force finishing activity com.shkmishra.lyrically/.MainActivity
```
